### ISSUE TITLE
Push latest version `0.19.2` to DockerHub

### ISSUE THREAD

**Issue by Scottapotamas** [jpconstantineau/Docker_Arduino_CLI#2]
I noticed the action to check for new versions has been working correctly and commits for those versions exist, but none of the `0.19.x` versions have been built/released.

There were some annoying bugs in `arduino-cli` which affect the currently published image version (https://github.com/arduino/arduino-cli/pull/1466)

Thanks!

**Comment by jpconstantineau** [comment]
I just updated the action to trigger the builds and push to both dockerhub and github container registry.  Should be up to date now...
